<a href="https://colab.research.google.com/github/WilsonRomao/estoque_farmacia_sesau/blob/main/backend/pipeline/analise_relatorio_geral.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports e constantes

In [2]:
import pandas as pd

try:
    from google.colab import drive
    drive.mount('/content/drive')
    BASE_PATH = '/content/drive/MyDrive/UFMS - SISTEMAS DE INFORMAÇÃO/PET SAUDE/bronze/'
except ImportError:
    print("Google Colab não detectado. Continuando para ambiente fora do colab.")
    import os
    # Caminho para a pasta contendo os arquivos Excel
    BASE_PATH = os.getcwd()
    # subir um nível para acessar a pasta "uploads"
    UPLOAD_PATH = os.path.dirname(BASE_PATH)
    EXCEL_FOLDER = os.path.join(UPLOAD_PATH, 'uploads','Toda a rede.xls')

Google Colab não detectado. Continuando para ambiente fora do colab.

# Extração dos dados



# Extrair os dados de cada arquivo Excel e armazenar em um DataFrame
def extract_data_from_excels(EXCEL_FOLDER):
    data_frames = []
    for file_name in os.listdir(EXCEL_FOLDER):
        if file_name.endswith('.xlsx') or file_name.endswith('.xls'):
            file_path = os.path.join(EXCEL_FOLDER, file_name)
            df = pd.read_excel(file_path, header=None)  # Ler o arquivo Excel sem considerar a primeira linha como cabeçalho
            data_frames.append(df)  
    # Concatenar todos os DataFrames em um único DataFrame
    final_df = pd.concat(data_frames, ignore_index=True)
    return final_df

In [ ]:
df = pd.read_excel(EXCEL_FOLDER,header=None, usecols=[1, 12]
df

TypeError: read_excel() got an unexpected keyword argument 'encolding'

# Transformação

### Tratando valores nulos e irrelevantes

In [7]:
#manter apenas as colunas 1 e 12
df = df[[1, 12]]
df

                                                      1          12
0                                                    NaN        NaN
1                                                    NaN        NaN
2                                                    NaN        NaN
3                                                Produto        NaN
4      Estabelecimento de Saúde:  SESAU DAF ALMOX BÁS...        NaN
...                                                  ...        ...
47127                                             Total:       20.0
47128                                                NaN        NaN
47129                                   Total Relatório:  9944075.0
47130                                                NaN        NaN
47131  SUS - Sistema único de Saúde     Ministério da...        NaN

[47132 rows x 2 columns]

In [8]:

#Drop em todas as linhas que não começem com "Estabelecimento" ou "BR" ou "Total:"
df = df[df[1].str.startswith(('Estabelecimento', 'BR', 'Total:'), na=False)]
    
df

                                                      1     12
4      Estabelecimento de Saúde:  SESAU DAF ALMOX BÁS...   NaN
6      BR0267618U0042 CARBAMAZEPINA  200 MG COMPRIMID...   NaN
7                                                 Total:   0.0
8          BR0267778U0042 PARACETAMOL  500 MG COMPRIMIDO   NaN
9                                                 Total:   0.0
...                                                  ...   ...
47121                                             Total:  30.0
47122  BR0395910 VALSARTANA + HIDROCLOROTIAZIDA 320 +...   NaN
47124                                             Total:  40.0
47125  BR0442230 VORTIOXETINA, BROMIDATO 5 MG COMPRIMIDO   NaN
47127                                             Total:  20.0

[33887 rows x 2 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33887 entries, 4 to 47127
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1       33887 non-null  object
 1   12      16837 non-null  float64
dtypes: float64(1), object(1)
memory usage: 794.2+ KB

In [10]:
# Cria uma nova coluna "estabelecimento" para armazenar o nome do estabelecimento de saúde correspondente;
df["estabelecimento"] = df[df[1].str.startswith('Estabelecimento', na=False)][1].str.replace('Estabelecimento de Saúde: ', '', regex=False)

df

/tmp/ipykernel_33667/2196997209.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["estabelecimento"] = df[df[1].str.startswith('Estabelecimento', na=False)][1].str.replace('Estabelecimento de Saúde: ', '', regex=False)

,1,12,estabelecimento
4,Estabelecimento de Saúde: SESAU DAF ALMOX BÁS...,NaN,SESAU DAF ALMOX BÁSICO CAMPO GRANDE
6,BR0267618U0042 CARBAMAZEPINA 200 MG COMPRIMID...,NaN,NaN
7,Total:,0.0,NaN
8,BR0267778U0042 PARACETAMOL 500 MG COMPRIMIDO,NaN,NaN
9,Total:,0.0,NaN
...,...,...,...
47121,Total:,30.0,NaN
47122,BR0395910 VALSARTANA + HIDROCLOROTIAZIDA 320 +...,NaN,NaN
47124,Total:,40.0,NaN
47125,"BR0442230 VORTIOXETINA, BROMIDATO 5 MG COMPRIMIDO",NaN,NaN
47127,Total:,20.0,NaN

In [11]:

# Remover a string "Estabelecimento de Saúde:" da nova coluna "estabelecimento";
df["estabelecimento"] = df["estabelecimento"].str.replace("Estabelecimento de Saúde:", "", case=False).str.strip()
df

/tmp/ipykernel_33667/3299101835.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["estabelecimento"] = df["estabelecimento"].str.replace("Estabelecimento de Saúde:", "", case=False).str.strip()

,1,12,estabelecimento
4,Estabelecimento de Saúde: SESAU DAF ALMOX BÁS...,NaN,SESAU DAF ALMOX BÁSICO CAMPO GRANDE
6,BR0267618U0042 CARBAMAZEPINA 200 MG COMPRIMID...,NaN,NaN
7,Total:,0.0,NaN
8,BR0267778U0042 PARACETAMOL 500 MG COMPRIMIDO,NaN,NaN
9,Total:,0.0,NaN
...,...,...,...
47121,Total:,30.0,NaN
47122,BR0395910 VALSARTANA + HIDROCLOROTIAZIDA 320 +...,NaN,NaN
47124,Total:,40.0,NaN
47125,"BR0442230 VORTIOXETINA, BROMIDATO 5 MG COMPRIMIDO",NaN,NaN
47127,Total:,20.0,NaN

In [12]:

# Preencher os valores nulos da nova coluna "estabelecimento" com o valor correspondente ao valor da linha não nula anterior da nova coluna "estabelecimento"
df["estabelecimento"] = df["estabelecimento"].ffill()
df

/tmp/ipykernel_33667/1422132165.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["estabelecimento"] = df["estabelecimento"].ffill()

,1,12,estabelecimento
4,Estabelecimento de Saúde: SESAU DAF ALMOX BÁS...,NaN,SESAU DAF ALMOX BÁSICO CAMPO GRANDE
6,BR0267618U0042 CARBAMAZEPINA 200 MG COMPRIMID...,NaN,SESAU DAF ALMOX BÁSICO CAMPO GRANDE
7,Total:,0.0,SESAU DAF ALMOX BÁSICO CAMPO GRANDE
8,BR0267778U0042 PARACETAMOL 500 MG COMPRIMIDO,NaN,SESAU DAF ALMOX BÁSICO CAMPO GRANDE
9,Total:,0.0,SESAU DAF ALMOX BÁSICO CAMPO GRANDE
...,...,...,...
47121,Total:,30.0,SESAU USF VILA COX SANTA LUZIA
47122,BR0395910 VALSARTANA + HIDROCLOROTIAZIDA 320 +...,NaN,SESAU USF VILA COX SANTA LUZIA
47124,Total:,40.0,SESAU USF VILA COX SANTA LUZIA
47125,"BR0442230 VORTIOXETINA, BROMIDATO 5 MG COMPRIMIDO",NaN,SESAU USF VILA COX SANTA LUZIA
47127,Total:,20.0,SESAU USF VILA COX SANTA LUZIA

In [11]:
# Dropar linhas que contêm "Estabelecimento" na coluna 1
df = df[~df[1].str.contains('Estabelecimento', case=True, na=False, regex=True)]
df.reset_index(drop=True, inplace=True) 
df

,1,12,estabelecimento
0,BR0267618U0042 CARBAMAZEPINA 200 MG COMPRIMID...,NaN,SESAU DAF ALMOX BÁSICO CAMPO GRANDE
1,Total:,0.0,SESAU DAF ALMOX BÁSICO CAMPO GRANDE
2,BR0267778U0042 PARACETAMOL 500 MG COMPRIMIDO,NaN,SESAU DAF ALMOX BÁSICO CAMPO GRANDE
3,Total:,0.0,SESAU DAF ALMOX BÁSICO CAMPO GRANDE
4,"BR0606841U0042 RIFAPENTINA, ASSOCIADA À ISONIA...",NaN,CTA - CENTRO DE TESTAGEM E ACONSELHAMENTO CAMP...
...,...,...,...
33669,Total:,30.0,SESAU USF VILA COX SANTA LUZIA
33670,BR0395910 VALSARTANA + HIDROCLOROTIAZIDA 320 +...,NaN,SESAU USF VILA COX SANTA LUZIA
33671,Total:,40.0,SESAU USF VILA COX SANTA LUZIA
33672,"BR0442230 VORTIOXETINA, BROMIDATO 5 MG COMPRIMIDO",NaN,SESAU USF VILA COX SANTA LUZIA
33673,Total:,20.0,SESAU USF VILA COX SANTA LUZIA

In [12]:
# criar mais duas colunas: "catmat" e 'medicamento' para armazenar as informações correspondentes da coluna 1 que começam com BR, dividindo a string da coluna 1 em duas partes: a parte que começa com "BR" e a parte que vem depois de do primeiro espaço em branco após "BR"
df["catmat"] = df[1].str.extract(r'(BR\S*)').copy()
df["medicamento"] = df[1].str.extract(r'BR\S*\s(.*)').copy()
df

/tmp/ipykernel_20753/1477717216.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["catmat"] = df[1].str.extract(r'(BR\S*)').copy()
/tmp/ipykernel_20753/1477717216.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["medicamento"] = df[1].str.extract(r'BR\S*\s(.*)').copy()

,1,12,estabelecimento,catmat,medicamento
0,BR0267618U0042 CARBAMAZEPINA 200 MG COMPRIMID...,NaN,SESAU DAF ALMOX BÁSICO CAMPO GRANDE,BR0267618U0042,CARBAMAZEPINA 200 MG COMPRIMIDO ELENCO ESTADUAL
1,Total:,0.0,SESAU DAF ALMOX BÁSICO CAMPO GRANDE,NaN,NaN
2,BR0267778U0042 PARACETAMOL 500 MG COMPRIMIDO,NaN,SESAU DAF ALMOX BÁSICO CAMPO GRANDE,BR0267778U0042,PARACETAMOL 500 MG COMPRIMIDO
3,Total:,0.0,SESAU DAF ALMOX BÁSICO CAMPO GRANDE,NaN,NaN
4,"BR0606841U0042 RIFAPENTINA, ASSOCIADA À ISONIA...",NaN,CTA - CENTRO DE TESTAGEM E ACONSELHAMENTO CAMP...,BR0606841U0042,"RIFAPENTINA, ASSOCIADA À ISONIAZIDA 300 + 300 ..."
...,...,...,...,...,...
33669,Total:,30.0,SESAU USF VILA COX SANTA LUZIA,NaN,NaN
33670,BR0395910 VALSARTANA + HIDROCLOROTIAZIDA 320 +...,NaN,SESAU USF VILA COX SANTA LUZIA,BR0395910,"VALSARTANA + HIDROCLOROTIAZIDA 320 + 12,5 MG C..."
33671,Total:,40.0,SESAU USF VILA COX SANTA LUZIA,NaN,NaN
33672,"BR0442230 VORTIOXETINA, BROMIDATO 5 MG COMPRIMIDO",NaN,SESAU USF VILA COX SANTA LUZIA,BR0442230,"VORTIOXETINA, BROMIDATO 5 MG COMPRIMIDO"
33673,Total:,20.0,SESAU USF VILA COX SANTA LUZIA,NaN,NaN

In [13]:
#preencier os valores nulos da coluna "catmat" com o valor correspondente ao valor da linha não nula anterior da coluna "catmat" e o mesmo para a coluna "medicamento"
df["catmat"] = df["catmat"].ffill()
df["medicamento"] = df["medicamento"].ffill()
df

/tmp/ipykernel_20753/1275007708.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["catmat"] = df["catmat"].ffill()
/tmp/ipykernel_20753/1275007708.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["medicamento"] = df["medicamento"].ffill()

,1,12,estabelecimento,catmat,medicamento
0,BR0267618U0042 CARBAMAZEPINA 200 MG COMPRIMID...,NaN,SESAU DAF ALMOX BÁSICO CAMPO GRANDE,BR0267618U0042,CARBAMAZEPINA 200 MG COMPRIMIDO ELENCO ESTADUAL
1,Total:,0.0,SESAU DAF ALMOX BÁSICO CAMPO GRANDE,BR0267618U0042,CARBAMAZEPINA 200 MG COMPRIMIDO ELENCO ESTADUAL
2,BR0267778U0042 PARACETAMOL 500 MG COMPRIMIDO,NaN,SESAU DAF ALMOX BÁSICO CAMPO GRANDE,BR0267778U0042,PARACETAMOL 500 MG COMPRIMIDO
3,Total:,0.0,SESAU DAF ALMOX BÁSICO CAMPO GRANDE,BR0267778U0042,PARACETAMOL 500 MG COMPRIMIDO
4,"BR0606841U0042 RIFAPENTINA, ASSOCIADA À ISONIA...",NaN,CTA - CENTRO DE TESTAGEM E ACONSELHAMENTO CAMP...,BR0606841U0042,"RIFAPENTINA, ASSOCIADA À ISONIAZIDA 300 + 300 ..."
...,...,...,...,...,...
33669,Total:,30.0,SESAU USF VILA COX SANTA LUZIA,BR0292791,"VALSARTANA + HIDROCLOROTIAZIDA 160 + 12,5 MG ..."
33670,BR0395910 VALSARTANA + HIDROCLOROTIAZIDA 320 +...,NaN,SESAU USF VILA COX SANTA LUZIA,BR0395910,"VALSARTANA + HIDROCLOROTIAZIDA 320 + 12,5 MG C..."
33671,Total:,40.0,SESAU USF VILA COX SANTA LUZIA,BR0395910,"VALSARTANA + HIDROCLOROTIAZIDA 320 + 12,5 MG C..."
33672,"BR0442230 VORTIOXETINA, BROMIDATO 5 MG COMPRIMIDO",NaN,SESAU USF VILA COX SANTA LUZIA,BR0442230,"VORTIOXETINA, BROMIDATO 5 MG COMPRIMIDO"
33673,Total:,20.0,SESAU USF VILA COX SANTA LUZIA,BR0442230,"VORTIOXETINA, BROMIDATO 5 MG COMPRIMIDO"

In [14]:
# Drop(remover) todas as linhas que começem com "BR" na coluna 1
df.drop(df[df[1].str.startswith('BR', na=False)].index, inplace=True)
df.reset_index(drop=True, inplace=True)
df

/tmp/ipykernel_20753/171872872.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(df[df[1].str.startswith('BR', na=False)].index, inplace=True)

,1,12,estabelecimento,catmat,medicamento
0,Total:,0.0,SESAU DAF ALMOX BÁSICO CAMPO GRANDE,BR0267618U0042,CARBAMAZEPINA 200 MG COMPRIMIDO ELENCO ESTADUAL
1,Total:,0.0,SESAU DAF ALMOX BÁSICO CAMPO GRANDE,BR0267778U0042,PARACETAMOL 500 MG COMPRIMIDO
2,Total:,0.0,CTA - CENTRO DE TESTAGEM E ACONSELHAMENTO CAMP...,BR0606841U0042,"RIFAPENTINA, ASSOCIADA À ISONIAZIDA 300 + 300 ..."
3,Total:,600.0,CTA - CENTRO DE TESTAGEM E ACONSELHAMENTO CAMP...,BR0467031U0042,DARUNAVIR 800 MG COMPRIMIDO
4,Total:,24630.0,CTA - CENTRO DE TESTAGEM E ACONSELHAMENTO CAMP...,BR0433687U0042,DOLUTEGRAVIR 50 MG COMP
...,...,...,...,...,...
16832,Total:,3.0,SESAU USF VILA COX SANTA LUZIA,BR0394103,RIVAROXABANA 10 MG COMPRIMIDO
16833,Total:,14.0,SESAU USF VILA COX SANTA LUZIA,BR0412091,RIVAROXABANA 20 MG COMPRIMIDO ELENCO ESTADUAL
16834,Total:,30.0,SESAU USF VILA COX SANTA LUZIA,BR0292791,"VALSARTANA + HIDROCLOROTIAZIDA 160 + 12,5 MG ..."
16835,Total:,40.0,SESAU USF VILA COX SANTA LUZIA,BR0395910,"VALSARTANA + HIDROCLOROTIAZIDA 320 + 12,5 MG C..."
16836,Total:,20.0,SESAU USF VILA COX SANTA LUZIA,BR0442230,"VORTIOXETINA, BROMIDATO 5 MG COMPRIMIDO"

In [17]:
df['quantidade'] = df[12].astype(int)
df

/tmp/ipykernel_20753/2788325772.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['quantidade'] = df[12].astype(int)

,1,12,estabelecimento,catmat,medicamento,quantidade
0,Total:,0.0,SESAU DAF ALMOX BÁSICO CAMPO GRANDE,BR0267618U0042,CARBAMAZEPINA 200 MG COMPRIMIDO ELENCO ESTADUAL,0
1,Total:,0.0,SESAU DAF ALMOX BÁSICO CAMPO GRANDE,BR0267778U0042,PARACETAMOL 500 MG COMPRIMIDO,0
2,Total:,0.0,CTA - CENTRO DE TESTAGEM E ACONSELHAMENTO CAMP...,BR0606841U0042,"RIFAPENTINA, ASSOCIADA À ISONIAZIDA 300 + 300 ...",0
3,Total:,600.0,CTA - CENTRO DE TESTAGEM E ACONSELHAMENTO CAMP...,BR0467031U0042,DARUNAVIR 800 MG COMPRIMIDO,600
4,Total:,24630.0,CTA - CENTRO DE TESTAGEM E ACONSELHAMENTO CAMP...,BR0433687U0042,DOLUTEGRAVIR 50 MG COMP,24630
...,...,...,...,...,...,...
16832,Total:,3.0,SESAU USF VILA COX SANTA LUZIA,BR0394103,RIVAROXABANA 10 MG COMPRIMIDO,3
16833,Total:,14.0,SESAU USF VILA COX SANTA LUZIA,BR0412091,RIVAROXABANA 20 MG COMPRIMIDO ELENCO ESTADUAL,14
16834,Total:,30.0,SESAU USF VILA COX SANTA LUZIA,BR0292791,"VALSARTANA + HIDROCLOROTIAZIDA 160 + 12,5 MG ...",30
16835,Total:,40.0,SESAU USF VILA COX SANTA LUZIA,BR0395910,"VALSARTANA + HIDROCLOROTIAZIDA 320 + 12,5 MG C...",40
16836,Total:,20.0,SESAU USF VILA COX SANTA LUZIA,BR0442230,"VORTIOXETINA, BROMIDATO 5 MG COMPRIMIDO",20

In [18]:
#dro par as colunas 1 e 12
df.drop(columns=[1, 12], inplace=True)
df

/tmp/ipykernel_20753/3520563774.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=[1, 12], inplace=True)

,estabelecimento,catmat,medicamento,quantidade
0,SESAU DAF ALMOX BÁSICO CAMPO GRANDE,BR0267618U0042,CARBAMAZEPINA 200 MG COMPRIMIDO ELENCO ESTADUAL,0
1,SESAU DAF ALMOX BÁSICO CAMPO GRANDE,BR0267778U0042,PARACETAMOL 500 MG COMPRIMIDO,0
2,CTA - CENTRO DE TESTAGEM E ACONSELHAMENTO CAMP...,BR0606841U0042,"RIFAPENTINA, ASSOCIADA À ISONIAZIDA 300 + 300 ...",0
3,CTA - CENTRO DE TESTAGEM E ACONSELHAMENTO CAMP...,BR0467031U0042,DARUNAVIR 800 MG COMPRIMIDO,600
4,CTA - CENTRO DE TESTAGEM E ACONSELHAMENTO CAMP...,BR0433687U0042,DOLUTEGRAVIR 50 MG COMP,24630
...,...,...,...,...
16832,SESAU USF VILA COX SANTA LUZIA,BR0394103,RIVAROXABANA 10 MG COMPRIMIDO,3
16833,SESAU USF VILA COX SANTA LUZIA,BR0412091,RIVAROXABANA 20 MG COMPRIMIDO ELENCO ESTADUAL,14
16834,SESAU USF VILA COX SANTA LUZIA,BR0292791,"VALSARTANA + HIDROCLOROTIAZIDA 160 + 12,5 MG ...",30
16835,SESAU USF VILA COX SANTA LUZIA,BR0395910,"VALSARTANA + HIDROCLOROTIAZIDA 320 + 12,5 MG C...",40
16836,SESAU USF VILA COX SANTA LUZIA,BR0442230,"VORTIOXETINA, BROMIDATO 5 MG COMPRIMIDO",20

In [19]:

# verificar catmats duplicados com o mesmo estabelecimento, caso verdadeiro, somar as quantidades e manter apenas uma linha para cada catmat e estabelecimento
df = df.groupby(['estabelecimento', 'catmat', 'medicamento'], as_index=False)['quantidade'].sum()   
df

,estabelecimento,catmat,medicamento,quantidade
0,CTA - CENTRO DE TESTAGEM E ACONSELHAMENTO CAMP...,BR0266788-1,NISTATINA 25.000 UI/G CREME VAGINAL 50 G,20
1,CTA - CENTRO DE TESTAGEM E ACONSELHAMENTO CAMP...,BR0267107U0013,FENITOÍNA SÓDICA 50 MG/ML SOLUÇÃO INJETÁVEL 5 ML,1
2,CTA - CENTRO DE TESTAGEM E ACONSELHAMENTO CAMP...,BR0267140U0042,AZITROMICINA 500 MG COMPRIMIDO ELENCO ESTADUAL,288
3,CTA - CENTRO DE TESTAGEM E ACONSELHAMENTO CAMP...,BR0267162U0004,"CLORETO DE POTÁSSIO 19,10% SOLUÇÃO INJETÁVEL 1...",5
4,CTA - CENTRO DE TESTAGEM E ACONSELHAMENTO CAMP...,BR0267194U0009,DIAZEPAM 5 MG/ML SOLUÇÃO INJETÁVEL 2 ML,0
...,...,...,...,...
14832,SESAU USF VILA COX SANTA LUZIA,BR0446251,"CARVÃO ATIVADO, EM PÓ, 8G",0
14833,SESAU USF VILA COX SANTA LUZIA,BR0446631U0042,ISONIAZIDA + RIFAMPICINA 150 + 300 MG COMPRIMIDO,380
14834,SESAU USF VILA COX SANTA LUZIA,BR0461492U0140,"AGULHA DESCARTÁVEL 4 MM X 0, 23 MM PARA CANETA...",100
14835,SESAU USF VILA COX SANTA LUZIA,BR0466098,"REAGENTE PARA DIAGNÓSTICO CLÍNICO 6, CONJUNTO ...",20
14836,SESAU USF VILA COX SANTA LUZIA,BR0619949,"EXTRATO MEDICINAL, PRÓPOLIS 100 MG/G CREME (F...",0

In [20]:
# save estoue in a json named estoque_processado_alves_pereira
df.to_json(BASE_PATH + '/estoque_geral.json', orient='records')
# # SAVA A CSV WITH THE SAME NAME
# df.to_csv(BASE_PATH + '/estoque_processado_alves_pereira.csv', index=False)